name: Code Formatter
on:
   workflow_dispatch:
   push:
      paths-ignore:
         - "!.github/**"

jobs:
   format:
      name: ESLint & Prettier
      if: ${{ github.actor != 'renovate[bot]' }}
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v4

         - name: Setup PNPM
           uses: pnpm/action-setup@v2
           with:
              run_install: |
                 - args: [--fix-lockfile, --ignore-scripts]
              version: ${{ vars.PNPM_VERSION }}

         - name: Setup Node
           uses: actions/setup-node@v4
           with:
              node-version: ${{ vars.NODE_VERSION }}
              cache: pnpm

         - name: Run ESLint
           run: pnpm run eslint:fix

         - name: Run Prettier
           run: pnpm run prettier

         - name: Automatically Commit Changed
           uses: stefanzweifel/git-auto-commit-action@v5
           with:
              push_options: "--force"
              commit_options: "--no-verify"
              commit_message: "chore: fix problems"
              skip_checkout: true
