name: Test
on: [workflow_dispatch, pull_request]

jobs:
   lint:
      name: ESLint
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v4
           with:
              token: ${{ secrets.GH_TOKEN_SUBMODULES }}
              submodules: true

         - name: Setup PNPM
           uses: pnpm/action-setup@v2
           with:
              run_install: |
                 - args: [--no-frozen-lockfile, --ignore-scripts]
              version: ${{ vars.PNPM_VERSION }}

         - name: Setup Node
           uses: actions/setup-node@v4
           with:
              node-version: ${{ vars.NODE_VERSION }}
              cache: pnpm

         - name: Run ESLint
           run: pnpm run eslint:lint

         - name: Run Build
           run: pnpm run build
